### ISSUE TITLE
ROCm 5.4.3 `malloc(): unsorted double linked list corrupted` on gfx1032 RX 6600

### ISSUE THREAD

**Issue by bdenhollander** [ROCm/ROCm#2034]
Environment: `Ubuntu 20.04.6 LTS` with Linux kernel `5.4.0` and amdgpu-pro `22.40-1538782.20.04` and ROCm `5.4.3`.

Attempting to run [VkFFT](https://github.com/DTolm/VkFFT) benchmark 1 on OpenCL fails with `malloc(): unsorted double linked list corrupted`

Repro:

1. Clone DTolm/VkFFT
2. Configure CMake to use VKFFT_BACKEND of 3 (OpenCL)
3. Build the executable
4. Run the benchmark `./Vulkan_FFT -o output.txt -vkfft 1`

```
(gdb) run
Starting program: /home/user/Documents/VkFFT/build-debug/Vulkan_FFT -o output.txt -vkfft 1
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff75c2700 (LWP 12561)]
[New Thread 0x7ffff6dc1700 (LWP 12562)]
[Thread 0x7ffff6dc1700 (LWP 12562) exited]
dlerror: libMesaOpenCL.so.1: cannot open shared object file: No such file or directory
[New Thread 0x7ffff61ff700 (LWP 12563)]
[Thread 0x7ffff61ff700 (LWP 12563) exited]
[New Thread 0x7ffff6577700 (LWP 12564)]
1 - VkFFT FFT + iFFT C2C benchmark 1D batched in double precision LUT
[New Thread 0x7ffff63ff700 (LWP 12569)]
[Thread 0x7ffff63ff700 (LWP 12569) exited]
[New Thread 0x7ffff63ff700 (LWP 12572)]
malloc(): unsorted double linked list corrupted

Thread 1 "Vulkan_FFT" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7a8a859 in __GI_abort () at abort.c:79
#2  0x00007ffff7af526e in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff7c1f298 "%s\n") at ../sysdeps/posix/libc_fatal.c:155
#3  0x00007ffff7afd2fc in malloc_printerr (str=str@entry=0x7ffff7c21ad8 "malloc(): unsorted double linked list corrupted") at malloc.c:5347
#4  0x00007ffff7b002ec in _int_malloc (av=av@entry=0x7ffff7c54b80 <main_arena>, bytes=bytes@entry=96) at malloc.c:3744
#5  0x00007ffff7b00adf in _int_memalign (av=av@entry=0x7ffff7c54b80 <main_arena>, alignment=alignment@entry=32, bytes=bytes@entry=16) at malloc.c:4684
#6  0x00007ffff7b049bc in _mid_memalign (address=<optimized out>, bytes=16, alignment=32) at malloc.c:3312
#7  __posix_memalign (size=16, alignment=<optimized out>, memptr=0x7fffffffc720) at malloc.c:5366
#8  __posix_memalign (memptr=0x7fffffffc720, alignment=<optimized out>, size=16) at malloc.c:5353
#9  0x00007ffff796435b in ?? () from /opt/rocm-5.4.3/lib/libamdocl64.so
#10 0x00007ffff796b832 in ?? () from /opt/rocm-5.4.3/lib/libamdocl64.so
#11 0x00007ffff792a908 in clCreateCommandQueueWithProperties () from /opt/rocm-5.4.3/lib/libamdocl64.so
#12 0x00007ffff792ad01 in clCreateCommandQueue () from /opt/rocm-5.4.3/lib/libamdocl64.so
#13 0x000055555556471f in transferDataFromCPU (vkGPU=0x7fffffffdc60, cpu_arr=0x7ffe5b948010, input_buffer=0x7fffffffc978, transferSize=1073741824)
    at /home/user/Documents/VkFFT/benchmark_scripts/vkFFT_scripts/src/utils_VkFFT.cpp:537
#14 0x000055555583a544 in sample_1_benchmark_VkFFT_double (vkGPU=0x7fffffffdc60, file_output=1, output=0x55555678ceb0, isCompilerInitialized=1)
    at /home/user/Documents/VkFFT/benchmark_scripts/vkFFT_scripts/src/sample_1_benchmark_VkFFT_double.cpp:170
#15 0x0000555555556c9c in launchVkFFT (vkGPU=0x7fffffffdc60, sample_id=1, file_output=true, output=0x55555678ceb0, userParams=0x0) at /home/user/Documents/VkFFT/Vulkan_FFT.cpp:304
#16 0x000055555555881d in main (argc=5, argv=0x7fffffffde98) at /home/user/Documents/VkFFT/Vulkan_FFT.cpp:891
```

[clinfo.txt](https://github.com/RadeonOpenCompute/ROCm/files/11193851/clinfo.txt)
[rocminfo.txt](https://github.com/RadeonOpenCompute/ROCm/files/11193852/rocminfo.txt)

**Comment by bdenhollander** [comment]
Retested with ROCm 6.0 and the issue no longer occurs.
